version: '3.9'
services:
  ### nginx #############################################################
  nginx:
    container_name: jm_nginx
    build: ./docker/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html/jinsei_mentor

  ### PHP ################################################################
  app:
    container_name: jm_app
    build: ./docker/php
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - .:/var/www/html/jinsei_mentor

  ### MySQL ###############################################################
  db:
    container_name: jm_db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/mycnf
      - jm_db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jm_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devuser
      MYSQL_PASSWORD: password
  # ### Next.js ###############################################################
  # view:
  #   container_name: jm_view
  #   build: ./docker/nextjs
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./view:/app
  #   command: sh -c "npm run dev"
  #   stdin_open: true
  #   tty: true

volumes:
  jm_db_volume:
